server:
  port: 8080
spring:
  application:
    name: "ScaffoldQuickStart"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5433
    database: ms_request
    schema: public
    username: ms_request
    password: ms_request

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG
    org.springdoc: DEBUG
    co.com.bancolombia: DEBUG

routes:
  paths:
    application:
      create: /api/v1/solicitud

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html #http://localhost:8080/webjars/swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: default
    url: /openapi.yaml
    # Para desarrollo local
    disable-swagger-default-url: false
  show-actuator: false

